name: Send Daily Email

on:
  schedule:
    - cron: '18 15 * * *'  # 한국시간 2AM (UTC 17시)
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      USER_EMAIL: jieun7349@gmail.com  # 받을 이메일 주소 넣기

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
